<?php

namespace Proxies\__CG__\CELiceoParaisoApp\CELiceoParaisoBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Administrador extends \CELiceoParaisoApp\CELiceoParaisoBundle\Entity\Administrador implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'CELiceoParaisoApp\\CELiceoParaisoBundle\\Entity\\Administrador' . "\0" . 'codigo', '' . "\0" . 'CELiceoParaisoApp\\CELiceoParaisoBundle\\Entity\\Administrador' . "\0" . 'nombre', '' . "\0" . 'CELiceoParaisoApp\\CELiceoParaisoBundle\\Entity\\Administrador' . "\0" . 'primerApellido', '' . "\0" . 'CELiceoParaisoApp\\CELiceoParaisoBundle\\Entity\\Administrador' . "\0" . 'segundoApellido', '' . "\0" . 'CELiceoParaisoApp\\CELiceoParaisoBundle\\Entity\\Administrador' . "\0" . 'telefono', '' . "\0" . 'CELiceoParaisoApp\\CELiceoParaisoBundle\\Entity\\Administrador' . "\0" . 'corrreo', '' . "\0" . 'CELiceoParaisoApp\\CELiceoParaisoBundle\\Entity\\Administrador' . "\0" . 'tipoAdministrador');
        }

        return array('__isInitialized__', '' . "\0" . 'CELiceoParaisoApp\\CELiceoParaisoBundle\\Entity\\Administrador' . "\0" . 'codigo', '' . "\0" . 'CELiceoParaisoApp\\CELiceoParaisoBundle\\Entity\\Administrador' . "\0" . 'nombre', '' . "\0" . 'CELiceoParaisoApp\\CELiceoParaisoBundle\\Entity\\Administrador' . "\0" . 'primerApellido', '' . "\0" . 'CELiceoParaisoApp\\CELiceoParaisoBundle\\Entity\\Administrador' . "\0" . 'segundoApellido', '' . "\0" . 'CELiceoParaisoApp\\CELiceoParaisoBundle\\Entity\\Administrador' . "\0" . 'telefono', '' . "\0" . 'CELiceoParaisoApp\\CELiceoParaisoBundle\\Entity\\Administrador' . "\0" . 'corrreo', '' . "\0" . 'CELiceoParaisoApp\\CELiceoParaisoBundle\\Entity\\Administrador' . "\0" . 'tipoAdministrador');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Administrador $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getCodigo()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getCodigo();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodigo', array());

        return parent::getCodigo();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', array($nombre));

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', array());

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrimerApellido($primerApellido)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrimerApellido', array($primerApellido));

        return parent::setPrimerApellido($primerApellido);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrimerApellido()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrimerApellido', array());

        return parent::getPrimerApellido();
    }

    /**
     * {@inheritDoc}
     */
    public function setSegundoApellido($segundoApellido)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSegundoApellido', array($segundoApellido));

        return parent::setSegundoApellido($segundoApellido);
    }

    /**
     * {@inheritDoc}
     */
    public function getSegundoApellido()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSegundoApellido', array());

        return parent::getSegundoApellido();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefono($telefono)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefono', array($telefono));

        return parent::setTelefono($telefono);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefono()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefono', array());

        return parent::getTelefono();
    }

    /**
     * {@inheritDoc}
     */
    public function setCorrreo($corrreo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCorrreo', array($corrreo));

        return parent::setCorrreo($corrreo);
    }

    /**
     * {@inheritDoc}
     */
    public function getCorrreo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCorrreo', array());

        return parent::getCorrreo();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoAdministrador(\CELiceoParaisoApp\CELiceoParaisoBundle\Entity\TipoAdministrador $tipoAdministrador = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoAdministrador', array($tipoAdministrador));

        return parent::setTipoAdministrador($tipoAdministrador);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoAdministrador()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoAdministrador', array());

        return parent::getTipoAdministrador();
    }

}
