ce_liceo_paraiso_homepage:
    path:     /home
    defaults: { _controller: CELiceoParaisoBundle:Default:index }
    
ce_liceo_paraiso_about_us:
    path:     /about_us
    defaults: { _controller: CELiceoParaisoBundle:Default:aboutUs }

ce_liceo_paraiso_ubication:
    path:     /ubication
    defaults: { _controller: CELiceoParaisoBundle:Default:showUbication }

ce_liceo_paraiso_credits:
    path:     /credits
    defaults: { _controller: CELiceoParaisoBundle:Default:showCredits }
   

   
ce_liceo_paraiso_login:
    path:     /login
    defaults: { _controller: CELiceoParaisoBundle:Administrator:login }
    
ce_liceo_paraiso_check_user:
    path:     /dashboard
    defaults: { _controller: CELiceoParaisoBundle:Administrator:checkUser }
    
ce_liceo_paraiso_change_pass:
    path:     /pass
    defaults: { _controller: CELiceoParaisoBundle:Administrator:changePass }
    
ce_liceo_paraiso_change_pass_form:
    path:     /form
    defaults: { _controller: CELiceoParaisoBundle:Administrator:changePassForm }
    
ce_liceo_paraiso_dashboard:
    path:     /administrator
    defaults: { _controller: CELiceoParaisoBundle:Administrator:homeAdmin }
    
ce_liceo_paraiso_institution_admin:
    path:     /institution
    defaults: { _controller: CELiceoParaisoBundle:Administrator:institution }
    
ce_liceo_paraiso_institution_history:
    path:     /institution_history
    defaults: { _controller: CELiceoParaisoBundle:Administrator:updateHistory }
    
ce_liceo_paraiso_institution_vision:
    path:     /institution_vision
    defaults: { _controller: CELiceoParaisoBundle:Administrator:updateVision }

ce_liceo_paraiso_institution_mision:
    path:     /institution_mision
    defaults: { _controller: CELiceoParaisoBundle:Administrator:updateMision }
    
ce_liceo_paraiso_institution_management:
    path:     /institution_management
    defaults: { _controller: CELiceoParaisoBundle:Administrator:updateManagement }
    
ce_liceo_paraiso_area_nocturn:
    path:     /area_nocturn
    defaults: { _controller: CELiceoParaisoBundle:Administrator:areaNocturn}
    
ce_liceo_paraiso_plan_national:
    path:     /plan_national
    defaults: { _controller: CELiceoParaisoBundle:Administrator:planNational}
    
ce_liceo_paraiso_responsable_area:
    path:     /area/{code}
    defaults: { _controller: CELiceoParaisoBundle:Administrator:responsableArea}

ce_liceo_paraiso_logout:
    path:   /login
    defaults: { _controller: CELiceoParaisoBundle:Administrator:logout }
    